# Generated by Django 4.2.4 on 2023-08-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[(1, "HOD"), (2, "Staff"), (3, "Student")],
                default="1",
                max_length=1,
            ),
        ),
    ]
