# Generated by Django 4.2.4 on 2023-08-27 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0002_alter_customuser_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancereport",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main_app.student"
            ),
        ),
    ]
