# Generated by Django 4.2.4 on 2023-08-27 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0004_alter_attendance_session_alter_attendance_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="staff",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main_app.staff",
            ),
        ),
    ]
